version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
      groups:
          security-patches:
              applies-to: security-updates
              patterns:
                  - '*'
          non-critical:
              applies-to: version-updates
              update-types:
                  - 'minor'
                  - 'patch'
              patterns:
                  - '*'
      open-pull-requests-limit: 5
